FROM python:3.11-slim

WORKDIR /app

# Copia lo script e le dipendenze
COPY heartRateSimulation.py .
COPY requirements-simulator.txt .

# Installa dipendenze Python
RUN pip install --no-cache-dir -r requirements-simulator.txt

# Variabili d'ambiente
ENV ENDPOINT_URL=http://backend:3001/api/v1/pushToKafka
ENV NUM_ATHLETES=20000
ENV SAMPLE_INTERVAL=5.0

# Entrypoint
CMD ["python", "heartRateSimulation.py"]
